
# 1. URLには「@より後ろの部分（ホスト名とDB名）」だけを書く
spring.datasource.url=jdbc:postgresql://dpg-d7thqeosfn5c73aohv40-a/anzan_db

# 2. ユーザー名だけを書く
spring.datasource.username=anzan_db_user

# 3. パスワードだけを書く
spring.datasource.password=8g9cVSMClC8j0Nto5MNSnIJ2RIAIGiIa

# Hibernateの設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
