# 1. ホスト名
spring.datasource.url=postgresql://anzan_db_user:8g9cVSMClC8j0Nto5MNSnIJ2RIAIGiIa@dpg-d7thqeosfn5c73aohv40-a.singapore-postgres.render.com/anzan_db

# 2. ユーザー名
spring.datasource.username=anzan_db_user

# 3. パスワード
spring.datasource.password=8g9cVSMClC8j0Nto5MNSnIJ2RIAIGiIa

# 4. 【重要】接続できない時でも「これはPostgresだよ」と教えてあげる設定を追加
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
