server.port=${PORT:8080}

spring.thymeleaf.cache=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.compression.enabled=true

# MySQL Connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/anzan_db?serverTimezone=JST}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:Y0ruGameKaihatsu2026!SQL}

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true